#!/bin/sh

MATCHES=$(git grep -n -E "(DevelopmentTeam|DEVELOPMENT_TEAM) =" .)
COUNT=$(echo -n "$MATCHES\c" | grep -cvE '(Shared.xcconfig|= "")')

if [ $COUNT -ne 0 ]; then
	ERRORS=$(echo -n "$MATCHES\c" | grep -vE '= ""')
	echo $COUNT
	echo "Remove Development Team specifications from project files:"
	echo "$ERRORS";
	exit 1;
fi
