/* config.h. Generated by cmake from config.h.cmake */

#ifndef TAGLIB_CONFIG_H
#define TAGLIB_CONFIG_H

/* Defined if your compiler supports some byte swap functions */
#define   HAVE_GCC_BYTESWAP 1
/* #undef HAVE_GLIBC_BYTESWAP */
/* #undef HAVE_MSC_BYTESWAP */
/* #undef HAVE_MAC_BYTESWAP */
/* #undef HAVE_OPENBSD_BYTESWAP */

/* Defined if your compiler supports some atomic operations */
#define   HAVE_GCC_ATOMIC 1
/* #undef HAVE_MAC_ATOMIC */
/* #undef HAVE_WIN_ATOMIC */
/* #undef HAVE_IA64_ATOMIC */

/* Defined if your compiler supports some safer version of vsprintf */
#define   HAVE_VSNPRINTF 1
/* #undef HAVE_VSPRINTF_S */

/* Defined if your compiler supports ISO _strdup */
/* #undef HAVE_ISO_STRDUP */

/* Defined if zlib is installed */
#define   HAVE_ZLIB 1

/* Indicates whether debug messages are shown even in release mode */
/* #undef TRACE_IN_RELEASE */

#define TESTS_DIR "/Users/nevack/work/taglib/tests/"

#endif
