/* config-taglib.h. Generated by cmake from config-taglib.h.cmake */

/* NOTE: only add something here if it is really needed by all of kdelibs.
   Otherwise please prefer adding to the relevant config-foo.h.cmake file,
   to minimize recompilations and increase modularity. */
/* Define if you have libz */
#define   HAVE_ZLIB 1

/* #undef NO_ITUNES_HACKS */
#define WITH_ASF 1
#define WITH_MP4 1
