.TH vgmplay "1" "November 10" "Valley Bell" "User Commands"
.nh
.SH NAME
vgmplay \- the official and always up-to-date player for all VGM files
.SH SYNOPSIS
\fBvgmplay\fP file
.SH KEYS
Cursor Left/Right - Seek 5 seconds backward/forward
.PP
Ctrl + Cursor Left/Right - Seek 1 minute backward/forward
.PP
Space - Pause
.PP
ESC/Q - Quit the program
.PP
F - Fade out
.PP
R - Restart current Track
.PP
PageUp/B - Previous Track
.PP
PageDown/N - Next Track
.SH SUPPORTED FILETYPES
Video Game Music Files (.vgm, .vgz)
.PP
Creative Music Files (.cmf)
.PP
DosBox RAW OPL Log Files (.dro)
.PP
Playlist files (.m3u)
.SH SUPPORTED CHIPS
.PP
SN76496 (2) (Sega PSG) and T6W28 (2) (NeoGeo Pocket custom)
.PP
YM2413 (1) (OPLL)
.PP
YM2612 (OPN2)
.PP
YM2151 (OPM)
.PP
SegaPCM
.PP
RF5C68
.PP
YM2203 (OPN)
.PP
YM2608 (OPNA)
.PP
YM2610/B (OPNB)
.PP
YM3812 (1) (OPL2)
.PP
YM3526 (1) (OPL)
.PP
Y8950 (1) (MSX AUDIO)
.PP
YMF262 (1) (OP3)
.PP
YMF278B (3) (OPL4)
.PP
YMF271 (OPLX)
.PP
YMZ280B
.PP
RF5C164 (Sega MegaCD PCM)
.PP
PWM (from Sega 32x)
.PP
AY8910 (MSX PSG)
.PP
GameBoy DMG
.PP
NES APU (incl. FDS)
.PP
MultiPCM
.PP
UPD7759
.PP
OKI6258 (Sharp X68000 ADPCM)
.PP
OKI6295
.PP
K051649
.PP
K054539
.PP
HuC6280 (PC Engine)
.PP
C140
.PP
K053260
.PP
Pokey (Atari)
.PP
QSound
.PP
SCSP (Saturn Custom Sound Processor, YMF292-F)
.PP
(1) This chip can be emulated via OPL Hardware (like Soundblaster sound cards).
.PP
(2) OPL hardware emulation is available, but software emulation is prefered. Hardware emulation is used if another chip activates HW emulation or FMForce is True.
(3) You need a sample ROM, called yrw801.rom, to make playback work. Place it in the directory where vgmplay lies or in /usr/local/share/vgmplay/.
.PP
OPL hardware emulation can be enabled by setting the "FMPort"-entry in the ini-file.
Under Linux the program must be run as root to use hardware FM.
.PP
It's possible to write Wave files by editing the "LogSound"-line in the ini-file.
Batch conversions are possible by opening a playlist.
FM hardware cannot be logged to Wave files.
.SH CONFIGURATION
vgmplay is configured in the file VGMPlay.ini, which should be located in $XDG_CONFIG_HOME/vgmplay (thus, by default ~/.config/vgmplay/VGMPlay.ini).  A sample configuration /usr/share/vgmplay/VGMPlay.ini is available for copying and general reference.
.SH BUGS
PauseEmulation is disabled under Linux if no FM Hardware is used.
.PP
You have to double-tap ESC to quit the program.
.PP
Sometimes MAME's sound cores tend to sound strange.
.SH COMMENTS
The T6W28 doesn't use MAME's T6W28 core. Instead the SN76496 core is modified to emulate the T6W28 with 2 SN76496 chips.
The SN76496 OPL emulation is okay, but it's impossible to get the noise sound right.
.PP
EMU2413 Emulator was added, because sometimes the one of MAME sounds strange.
The Gens YM2612 core was added for the same reason before MAME's YM2612 core was fixed.
.PP
.SH AUTHORS
This program was written by Valley Bell.
.PP
Almost all software emulators are from MAME (http://mamedev.org)
.PP
EMU2413 and Gens YM2612 were ported from Maxim's in_vgm
.PP
The YMF278B core was ported from openMSX
.PP
zlib compression by Jean-loup Gailly and Mark Adler is used
.PP
All custom OPL Mappers were written using MAME software emulators and the OPL2/3 programming guides by Jeffrey S. Lee and Vladimir Arnost
.PP
one YM2413 OPL Mapper was ported from MEKA.
.PP
The RF5C164 and PWM cores were ported from Gens/GS
.PP
The MAME YM2612 core was fixed with the help of Blargg's MAME YM2612 fix and Genesis Plus GX' YM2612 core
.PP
AdLibEmu (OPL2 and OPL3 core) was ported from DOSBox
.PP
The default HuC6280 core is from Ootake.
.PP
EMU2149, the alternative NES APU core and the NES FDS core were ported from rainwarrior's NSFPlay.
